name: autoexplorer
description: "Simple explorer-project"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  dio: ^5.8.0+1
  permission_handler: ^11.4.0
  flutter_svg: ^1.1.6
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  firebase_core: ^3.12.1
  # firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/img/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/favicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/img/favicon.png"
  windows:
    generate: true
    image_path: "assets/img/favicon.png"
  macos:
    generate: true
    image_path: "assets/img/favicon.png"