// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBxcMT4yyl7cDLAwHaLx0xUfc1pC_Y_DM',
    appId: '1:464216100441:web:020a5f94a14071ae3f6b48',
    messagingSenderId: '464216100441',
    projectId: 'autoexplorer-19425',
    authDomain: 'autoexplorer-19425.firebaseapp.com',
    storageBucket: 'autoexplorer-19425.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUuR9VqA3tHAcc4iEPtU07SawyUI7otko',
    appId: '1:464216100441:android:7ee9982b6ffcc3923f6b48',
    messagingSenderId: '464216100441',
    projectId: 'autoexplorer-19425',
    storageBucket: 'autoexplorer-19425.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDerKRTjpFSI9k-G3fQTNQp4aTcVQ9vsrs',
    appId: '1:464216100441:ios:23f0a6bf6121d5303f6b48',
    messagingSenderId: '464216100441',
    projectId: 'autoexplorer-19425',
    storageBucket: 'autoexplorer-19425.firebasestorage.app',
    iosBundleId: 'com.example.autoexplorer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDerKRTjpFSI9k-G3fQTNQp4aTcVQ9vsrs',
    appId: '1:464216100441:ios:23f0a6bf6121d5303f6b48',
    messagingSenderId: '464216100441',
    projectId: 'autoexplorer-19425',
    storageBucket: 'autoexplorer-19425.firebasestorage.app',
    iosBundleId: 'com.example.autoexplorer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBxcMT4yyl7cDLAwHaLx0xUfc1pC_Y_DM',
    appId: '1:464216100441:web:5fb26700fed598223f6b48',
    messagingSenderId: '464216100441',
    projectId: 'autoexplorer-19425',
    authDomain: 'autoexplorer-19425.firebaseapp.com',
    storageBucket: 'autoexplorer-19425.firebasestorage.app',
  );
}
